version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/opt/static/jrasp
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
